import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <script
          dangerouslySetInnerHTML={{
            __html: `
          (function () {
            const getTheme = localStorage.getItem("theme");
            const theme = document.documentElement.dataset.theme;
            if (getTheme) {
              document.documentElement.dataset.theme = getTheme;
            }
            if (!getTheme && !theme) {
              document.documentElement.dataset.theme = "light";
            }
          })();
          `,
          }}
        />
      </body>
    </html>
  );
}
