import {
  GlobalStyles,
  SetupTheme,
  SetupThemeScript
} from '@stellaria/supernova';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import themes from '../themes';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SetupTheme default="light" themes={themes} />
        <SetupThemeScript default="light" />
        {children}
        <GlobalStyles />
      </body>
    </html>
  );
}
